import React, { useState } from "react";
import { Sparkles, FileText, Plus, FileDown, Presentation, Link2, Type, HelpCircle, GripVertical, Check, BarChart3, Quote, AlertCircle } from "lucide-react";

interface OutlineItem {
  id: string;
  num: number;
  label: string;
  isAi?: boolean;
}

const INITIAL_OUTLINE: OutlineItem[] = [
  { id: "1", num: 1, label: "Executive Summary", isAi: true },
  { id: "2", num: 2, label: "Methodology" },
  { id: "3", num: 3, label: "Key Findings", isAi: true },
  { id: "4", num: 4, label: "Scheduling Analysis" },
  { id: "5", num: 5, label: "Communication Analysis" },
  { id: "6", num: 6, label: "Demographic Insights" },
  { id: "7", num: 7, label: "Recommendations" },
  { id: "8", num: 8, label: "Appendix" },
];

export default function Reports() {
  const [outline, setOutline] = useState<OutlineItem[]>(INITIAL_OUTLINE);
  const [selectedOutlineId, setSelectedOutlineId] = useState("3");
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  const showToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 3500);
  };

  const handleExportPdf = () => {
    showToast("Opening system print dialog for PDF export...");
    setTimeout(() => {
      window.print();
    }, 400);
  };

  const handleCopyLink = () => {
    navigator.clipboard.writeText("https://inspin.io/report/customer-satisfaction-2026");
    showToast("Shareable report link copied to clipboard!");
  };

  const handleExportPpt = () => {
    showToast("Generating PowerPoint deck (.pptx)... Download ready.");
  };

  return (
    <div className="flex-1 flex flex-row h-[calc(100vh-120px)] relative overflow-hidden bg-[#f4f7f6]">
      
      {/* Outline Column (Left Panel) */}
      <div className="w-[240px] shrink-0 border-r border-slate-200/80 bg-white/50 backdrop-blur-md flex flex-col p-4 gap-4 overflow-y-auto">
        <div>
          <span className="text-[11px] font-semibold text-slate-500 uppercase tracking-wider block mb-3">
            Report Outline
          </span>
          <div className="flex flex-col gap-1">
            {outline.map((item) => (
              <div
                key={item.id}
                onClick={() => setSelectedOutlineId(item.id)}
                className={`group flex items-center gap-2 p-2 rounded-xl text-[13px] font-medium transition-all cursor-pointer ${
                  selectedOutlineId === item.id
                    ? "bg-[#e8f7f0] text-[#059669]"
                    : "text-slate-600 hover:bg-slate-100/50"
                }`}
              >
                <GripVertical className="size-3.5 text-slate-400 opacity-0 group-hover:opacity-100 transition-opacity" />
                <span className="text-slate-400 font-semibold min-w-[14px]">
                  {item.num}
                </span>
                <span className="truncate flex-1">{item.label}</span>
                {item.isAi && (
                  <Sparkles className="size-3.5 text-indigo-500 shrink-0" />
                )}
              </div>
            ))}
          </div>
        </div>

        <button className="flex items-center justify-center gap-2 w-full py-2.5 rounded-xl border border-dashed border-slate-300 text-slate-500 text-[13px] font-semibold hover:bg-white hover:border-slate-400 transition-all cursor-pointer mt-2">
          <Plus className="size-4" />
          Add Section
        </button>
      </div>

      {/* Center Viewport (Editor Sheet) */}
      <div className="flex-1 overflow-y-auto p-[40px] flex justify-center items-start">
        <div className="w-full max-w-[760px] bg-white rounded-[24px] border border-slate-200/80 shadow-md flex flex-col p-8 min-h-[900px] relative">
          
          {/* Document Header */}
          <div className="flex flex-col gap-4 border-b border-slate-100 pb-6 mb-6">
            <h1 className="font-['Inter:Bold',sans-serif] font-bold text-slate-800 text-[26px] leading-tight">
              Customer Satisfaction Survey 2026 — Research Report
            </h1>
            <div className="flex items-center gap-3">
              <span className="flex items-center gap-1 px-2.5 py-1 bg-purple-50 text-purple-700 text-[11px] font-bold rounded-lg border border-purple-100">
                <Sparkles className="size-3 text-purple-600" />
                Generated by InSpin AI
              </span>
              <span className="text-[12px] text-slate-400 font-medium">
                Last edited on Jul 15, 2026
              </span>
            </div>
          </div>

          {/* Section: Key Findings */}
          <div className="flex flex-col gap-6">
            <h2 className="font-['Inter:Bold',sans-serif] font-bold text-slate-800 text-[18px]">
              3. Key Findings
            </h2>

            {/* AI Summary Highlight Box */}
            <div className="border-l-4 border-purple-500 bg-purple-50/30 p-4 rounded-r-xl">
              <p className="text-[14px] text-slate-700 leading-relaxed font-medium">
                Our analysis of <span className="font-bold text-slate-900">2,847 responses</span> reveals scheduling flexibility as the dominant concern, with a <span className="font-bold text-[#8b5cf6]">34% increase</span> in negative sentiment since Q1 policy changes. Engineering and Operations departments are most impacted.
              </p>
            </div>

            {/* Replicated Satisfaction Table */}
            <div className="flex flex-col gap-4 mt-2">
              <div className="flex justify-between items-center">
                <span className="text-[11px] font-semibold text-slate-500 uppercase tracking-wider">
                  Satisfaction by Theme (% Positive Response)
                </span>
                <span className="text-[11px] text-slate-400">Sample: 2.8k respondents</span>
              </div>

              <div className="flex flex-col gap-3">
                {[
                  { name: "Scheduling", pct: 28 },
                  { name: "Communication", pct: 45 },
                  { name: "Equipment", pct: 72 },
                  { name: "Travel", pct: 63 },
                  { name: "Payment", pct: 81 },
                ].map((row) => (
                  <div key={row.name} className="flex items-center justify-between text-[13px] font-semibold text-slate-700">
                    <span className="w-28 shrink-0">{row.name}</span>
                    <div className="flex-1 h-2.5 bg-slate-100 rounded-full mx-4 overflow-hidden relative">
                      <div
                        className="h-full bg-emerald-500 rounded-full transition-all duration-500"
                        style={{ width: `${row.pct}%` }}
                      />
                    </div>
                    <span className="w-8 text-right">{row.pct}%</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Description Text */}
            <p className="text-[14px] text-slate-600 leading-relaxed mt-4">
              The severe drop in Scheduling satisfaction highlights a direct link to operational churn indicators. Below, we observe qualitative responses confirming that rigid scheduling windows conflict with regional client commitments.
            </p>

            {/* Evidence Card */}
            <div className="border border-[#059669]/30 bg-emerald-50/10 p-5 rounded-[16px] shadow-sm flex flex-col gap-3 relative mt-2">
              <div className="flex justify-between items-center">
                <span className="text-[10px] font-bold text-[#059669] uppercase tracking-wider">
                  Evidence Block — Respondent #419
                </span>
                <div className="text-slate-400">
                  <GripVertical className="size-4" />
                </div>
              </div>
              <p className="text-[13.5px] text-slate-800 font-medium italic leading-relaxed">
                "The new scheduling rules mean I have to wait up to 4 hours between field sessions. It's completely impractical for our local workflow and forces everyone to work overtime."
              </p>
              <div className="border-t border-slate-100 pt-2 flex items-center justify-between">
                <span className="text-[11px] text-[#059669] font-semibold">
                  Currently selected / editable
                </span>
              </div>
            </div>
          </div>

          {/* Spacer */}
          <div className="flex-1 min-h-[80px]" />

          {/* Footer */}
          <div className="border-t border-slate-100 pt-4 flex items-center justify-between text-[11px] font-semibold text-slate-400">
            <span>RideShare UX Report Draft v4</span>
            <span>Page 3 of 12</span>
          </div>

        </div>
      </div>

      {/* Assist Panel (Right Side Panel) */}
      <div className="w-[260px] shrink-0 border-l border-slate-200/80 bg-white/50 backdrop-blur-md flex flex-col p-4 gap-6 overflow-y-auto">
        
        {/* Insert Element Section */}
        <div className="flex flex-col gap-2.5">
          <span className="text-[11px] font-semibold text-slate-500 uppercase tracking-wider block">
            Insert Element
          </span>
          <div className="grid grid-cols-2 gap-2 text-[12px] font-semibold">
            <button className="flex items-center gap-1.5 p-2 bg-white border border-slate-200 rounded-xl text-slate-700 hover:bg-slate-50 cursor-pointer">
              <BarChart3 className="size-3.5 text-slate-500" />
              Chart
            </button>
            <button className="flex items-center gap-1.5 p-2 bg-white border border-slate-200 rounded-xl text-slate-700 hover:bg-slate-50 cursor-pointer">
              <Quote className="size-3.5 text-slate-500" />
              Evidence
            </button>
            <button className="flex items-center gap-1.5 p-2 bg-white border border-slate-200 rounded-xl text-slate-700 hover:bg-slate-50 cursor-pointer">
              <AlertCircle className="size-3.5 text-slate-500" />
              Finding
            </button>
            <button className="flex items-center gap-1.5 p-2 bg-purple-50 border border-purple-200 rounded-xl text-purple-700 hover:bg-purple-100/50 cursor-pointer col-span-2 justify-center">
              <Sparkles className="size-3.5 text-purple-600" />
              AI Summary
            </button>
          </div>
        </div>

        {/* Export Report Section */}
        <div className="flex flex-col gap-2.5">
          <span className="text-[11px] font-semibold text-slate-500 uppercase tracking-wider block">
            Export Report
          </span>
          <div className="flex flex-col gap-2 text-[12px] font-semibold">
            <button
              type="button"
              onClick={handleExportPdf}
              className="flex items-center gap-2 px-3 py-2 bg-[#e8f7f0] border border-[#a7f3d0] rounded-xl text-[#059669] hover:bg-[#d1fae5] active:scale-95 transition-all cursor-pointer focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500"
            >
              <FileDown className="size-4" />
              PDF (Standard)
            </button>
            <button
              type="button"
              onClick={handleExportPpt}
              className="flex items-center gap-2 px-3 py-2 bg-white border border-slate-200 rounded-xl text-slate-700 hover:bg-slate-50 active:scale-95 transition-all cursor-pointer focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-400"
            >
              <Presentation className="size-4 text-slate-400" />
              PowerPoint Slides
            </button>
            <button
              type="button"
              onClick={handleCopyLink}
              className="flex items-center gap-2 px-3 py-2 bg-white border border-slate-200 rounded-xl text-slate-700 hover:bg-slate-50 active:scale-95 transition-all cursor-pointer focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-400"
            >
              <Link2 className="size-4 text-slate-400" />
              Share Access Link
            </button>
          </div>
        </div>

        {/* AI Assist Section */}
        <div className="flex flex-col gap-2.5">
          <span className="text-[11px] font-semibold text-purple-700 uppercase tracking-wider block flex items-center gap-1">
            <Sparkles className="size-3.5 text-purple-600" />
            InSpin AI Assist
          </span>
          <div className="flex flex-col gap-1 text-[12px] font-medium text-slate-700">
            {["Rewrite Section", "Add Evidence", "Suggest Charts", "Improve Clarity"].map((item) => (
              <button
                key={item}
                type="button"
                onClick={() => showToast(`AI Assist: Executing "${item}"...`)}
                className="flex items-center gap-2 px-3 py-2 text-left rounded-xl hover:bg-slate-100/50 cursor-pointer active:scale-95 transition-all"
              >
                <Sparkles className="size-3 text-purple-500" />
                {item}
              </button>
            ))}
          </div>
        </div>

        {/* Spacer */}
        <div className="flex-1" />

        {/* Preview as PDF Button */}
        <button
          type="button"
          onClick={handleExportPdf}
          className="w-full py-2.5 rounded-xl bg-[#059669] hover:bg-[#047857] active:scale-95 text-white font-bold text-[13px] transition-all cursor-pointer shadow-sm shadow-emerald-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500"
        >
          Preview as PDF
        </button>

      </div>

      {/* Floating Toast Notification */}
      {toastMessage && (
        <div className="absolute bottom-6 left-1/2 -translate-x-1/2 bg-slate-900/90 backdrop-blur-md text-white text-[13px] font-semibold px-4 py-2.5 rounded-2xl shadow-xl border border-slate-700/50 z-50 flex items-center gap-2 animate-in fade-in slide-in-from-bottom-3 duration-200">
          <Check className="size-4 text-emerald-400 shrink-0" />
          <span>{toastMessage}</span>
        </div>
      )}

    </div>
  );
}
